language: python
cache: pip
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
  - python setup.py develop
script:
  - py.test --cov=latest_blender_url tests/
after_success:
  - codecov
